ALTER TABLE study_exercises 
ADD COLUMN IF NOT EXISTS level TEXT,
ADD COLUMN IF NOT EXISTS module_slug TEXT,
ADD COLUMN IF NOT EXISTS active BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS sort_order INTEGER;